name: Build UWP App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Restore NuGet packages
      run: |
        nuget restore AllLive.sln

    - name: Build Solution
      run: |
        msbuild AllLive.sln /p:Platform=x64 /p:AppxBundlePlatforms="x64" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload /p:Configuration=Release

    - name: Upload MSIX Package
      uses: actions/upload-artifact@v4
      with:
        # artifact的名称，在下载时会用到
        name: AllLive-MSIX
        # 要上传的文件或目录的路径。支持通配符。
        path: .\AllLive.UWP\AppPackages\**\*_x64.msixbundle

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        files: .\AllLive.UWP\AppPackages\*_x64.msixbundle
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}